<?php

return [
    'accepted' => 'Vous devez accepter :attribute.',
    'active_url' => ':attribute n\'est pas une URL valide.',
    'after' => ':attribute doit Ãªtre une date ultÃ©rieure Ã  :date.',
    'after_or_equal' => ':attribute doit Ãªtre une date postÃ©rieure ou Ã©gale :date.',
    'alpha' => ':attribute ne peut contenir que des lettres.',
    'alpha_dash' => ':attribute ne peut contenir que des lettres, chiffres et tirets.',
    'alpha_num' => ':attribute ne peut contenir que des lettres et chiffres.',
    'latin' => ':attribute doit seulement contenir des lettres de l\'alphabet Latin ISO basic.',
    'latin_dash_space' => ':attribute doit seulement contenir des lettres de l\'alphabet Latin ISO basic, nombres, tiret, trait d\'union et espaces.',
    'array' => ':attribute doit Ãªtre un tableau.',
    'before' => ':attribute doit Ãªtre une date antÃ©rieure Ã  :date.',
    'before_or_equal' => ':attribute doit Ãªtre une date postÃ©rieure ou Ã©gale  Ã  :date.',
    'between' => [
        'numeric' => ':attribute doit Ãªtre compris entre :min et :max.',
        'file' => ':attribute doit Ãªtre compris entre :min et :max kilobytes.',
        'string' => ':attribute doit Ãªtre compris en :min et :max caractÃ¨res.',
        'array' => ':attribute doit Ãªtre compris en :min et :max items.',
    ],
    'boolean' => ':attribute doit Ãªtre \"Vrai\" ou \"Faux\".',
    'confirmed' => 'La confirmation :attribute ne correspond pas.',
    'current_password' => 'Le mot de passe est incorrect.',
    'date' => ':attribute n\'est pas une date valide.',
    'date_equals' => ':attribut doit Ãªtre une date Ã©gale Ã  :date.',
    'date_format' => ':attribute ne correspond pas au format :format.',
    'different' => ':attribute et :other doivent Ãªtre diffÃ©rents.',
    'digits' => ':attribute doit un nombre de type :digit.',
    'digits_between' => 'La valeur du nombre :attribute doit Ãªtre comprise entre :min et :max.',
    'dimensions' => 'Les dimensions de l\'image :attribute ne sont pas valides.',
    'distinct' => 'Le champ :attribute comporte une valeur en double',
    'email' => ':attribute doit Ãªtre une adresse e-mail valide',
    'ends_with' => ':attribut doit se terminer par l\'un des Ã©lÃ©ments following:: valeurs.',
    'exists' => ':attribute n\'est pas valide',
    'file' => ':attribute doit Ãªtre un fichier',
    'filled' => 'Le champ :attribute est requis',
    'gt' => [
        'numeric' => ':attribute doit Ãªtre plus grand que :value.',
        'file' => ':attribute doit Ãªtre plus grand que :value kilobytes.',
        'string' => ':attribute doit Ãªtre plus grand que :value caractÃ¨res.',
        'array' => ':attribute doit avoir plus que :value items.',
    ],
    'gte' => [
        'numeric' => ':attribute doit Ãªtre plus grand que ou Ã©gal Ã  :value.',
        'file' => ':attribute doit Ãªtre plus grand que ou Ã©gal Ã  :value kilobytes.',
        'string' => ':attribute doit Ãªtre plus grand que ou Ã©gal Ã  :value caractÃ¨res.',
        'array' => ':attribute doit avoir :value items ou plus',
    ],
    'image' => ':attribute doit Ãªtre une image',
    'in' => 'La selection :attribute est invalide',
    'in_array' => ':attribute champ n\'existe pas dans :other',
    'integer' => ':attribute doit Ãªtre un entier.',
    'ip' => ':attribute doit Ãªtre une ip valide',
    'ipv4' => ':attribute doit Ãªtre une ip V4 valide',
    'ipv6' => ':attribute doit Ãªtre une ip V6 valide',
    'json' => ':attribute doit Ãªtre une chaine de caractÃ¨re JSON valide',
    'lt' => [
        'numeric' => ':attribute doit Ãªtre moins que :value.',
        'file' => ':attribute doit Ãªtre moins que :value kilobytes.',
        'string' => ':attribute doit Ãªtre moins que :value characters.',
        'array' => ':attribute doit avoir moins que :value items.',
    ],
    'lte' => [
        'numeric' => ':attribute doit Ãªtre moins que ou Ã©gal :value.',
        'file' => ':attribute doit Ãªtre moins que ou Ã©gal :value kilobytes.',
        'string' => ':attribute doit Ãªtre moins que ou Ã©gal :value characters.',
        'array' => ':attribute ne doit pas avoir plus que :value items.',
    ],
    'max' => [
        'numeric' => ':attribute ne peut pas Ãªtre plus grand que :max.',
        'file' => ':attribute ne doit pas Ãªtre plus grand que :max kilobytes.',
        'string' => ':attribute ne peut pas Ãªtre plus grand que :max characters.',
        'array' => ':attribute ne doit pas avoir plus que :max items.',
    ],
    'mimes' => ':attribute doit Ãªtre un fichier de type: :values.',
    'mimetypes' => ':attribute doit Ãªtre un fichier de type: :values.',
    'min' => [
        'numeric' => ':attribute doit Ãªtre au minimum :min.',
        'file' => ':attribute doit Ãªtre au minimum :min kilobytes.',
        'string' => ':attribute doit Ãªtre au moins :min caractÃ¨res.',
        'array' => ':attribute doit avoir au minimum :min items.',
    ],
    'not_in' => 'La selection :attribute est invalide.',
    'not_regex' => 'Le format :attribute est invalide.',
    'numeric' => ':attribute doit Ãªtre un nombre',
    'password' => 'Le mot de passe est incorrect',
    'present' => ':attribute champ doit Ãªtre prÃ©sent.',
    'regex' => ':attribute n\'est pas au bon format',
    'required' => ':attribute champ est requis.',
    'required_if' => ':attribute champ est requis lorsque :other est :value.',
    'required_unless' => ':attribute champ est requis Ã  moins que :other est dans :values.',
    'required_with' => ':attribute champ est requis lorsque :values est prÃ©sent.',
    'required_with_all' => ':attribute champ est requis lorsque :values est prÃ©sent.',
    'required_without' => ':attribute champ est requis lorsque :values n\'est pas prÃ©sent.',
    'required_without_all' => ':attribute champ est requis lorsque aucun de :values sont prÃ©sents',
    'same' => ':attribute et :other doivent correspondre.',
    'size' => [
        'numeric' => ':attribute doit Ãªtre :size.',
        'file' => ':attribute doit Ãªtre :size kilobytes.',
        'string' => ':attribute doit Ãªtre de :size caractÃ¨res.',
        'array' => ':attribute doit contenir :size Ã©lÃ©ments.',
    ],
    'starts_with' => ':attribut doit commencer par l\'un des Ã©lÃ©ments suivant :values.',
    'string' => ':attribute doit Ãªtre une chaine de caractÃ¨res',
    'timezone' => ':attribute doit Ãªtre une zone valide.',
    'unique' => ':attribute a dÃ©jÃ  Ã©tÃ© pris.',
    'uploaded' => ':attribute Ã©chec de l\'upload',
    'url' => ':attribute au format invalide',
    'uuid' => ':attribut doit Ãªtre un UUID valide.',
    'custom' => [
        'attribute-name' => [
            'rule-name' => 'custom-message',
        ],
    ],
    'reserved_word' => ':attribute contient un mot rÃ©servÃ©.',
    'dont_allow_first_letter_number' => 'Le champ  \":input\"  ne peut pas commencer par un chiffre',
    'exceeds_maximum_number' => 'L\'attribut sÃ©lectionnÃ© n\'est pas valide.',
    'db_column' => ':attribute doit seulement contenir des lettres de l\'alphabet Latin ISO basic, nombres, tiret et ne peut commencer par un nombre.',
    'attributes' => [],

];
